### ISSUE TITLE
Problem uploading...

### ISSUE THREAD

**Issue by ychuang-tw** [google/skicka#63]
I tried to get & compile the latest skicka using the recommended command:
go get github.com/google/skicka

however when I tried to upload a file with specified path such as this:
skicka upload ./funny.mkv /Mov_UL
I have made sure that the Mov_UL folder already existed before giving the command. However, the upload process is a success. But when I check with the web browser, it doesn't upload as expected. I got a file named "Mov_UL" (which was the specified folder name) and when I tried to open it, it gave such error message: 
![error_msg](https://cloud.githubusercontent.com/assets/10228460/6880667/b90f3cd0-d578-11e4-95b3-69ed9015a2d4.jpg)) I tried another command such as:
skicka upload ./funny.mkv /Mov_UL/ (added a tailed slash) but still not working correctly.

Please help. skicka is quite a command with very friendly interface. I want to use it constantly!

Thanks

**Comment by ychuang-tw** [comment]
[Update] It seems that there's some problem getting the latest version of skicka using the command:
go get github.com/google/skicka
The problem solved after I manually download the whole zip file, extract it and build it using:
go build github.com/google/skicka
I will check if the large size file problem is still there.

**Comment by mmp** [comment]
I've spent some time trying to reproduce this, but haven't been able to. From that error message, my guess is that there may have been a temporary issue with the Google Drive web pages, rather than a skicka bug.

If this happens again, can you try running
```
skicka ls -ll /Mov_UL
```
and see if the output is reasonable? Could you also try re-downloading the file with skicka:
```
skicka download /Mov_UL/funny.mkv funny_new.mkv
```
and see if a) that runs without error, and b) the file contents match.

That information would be helpful for further debugging this if you see it again.

Thanks!

**Comment by mmp** [comment]
Closing under the assumption this was a transient issue with the Drive web UI.
